### ISSUE TITLE
Help building POPF on MAC OS (Mojave)

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [aldukeman/popf2#1]
I'm trying to build POPF on my MAC.  I have installed all the COIN-OR dependencies from Homebrew; have GCC8.3, perl, bison, and flex.  I've fixed some cmake issues which now allow cmake to find cbc, cgl, clp, coinutils, and osi.  However, when I `make`, I get the following errors and compilation stops.  Note that from the output, the **parser** appears to have built correctly, and tests with IPC sample problems confirms that it's working fine.  It would be nice if I could get the rest of POPF working as well.  I need a little assistance with the following two questions before I can proceed.

1) Would someone be able to help me with understanding the YACC and SED errors (*note I'm running the Mac version of SED which isn't quite the same as GNU SED*).  I've looked through the code but can't find where this is taking place.
2) I've tried to find some information about the `no matching function for call to object of type 'const Inst::ConstSymbolLT'` error on google, but haven't been able to find anything.  Sounds to me like a BISON related problem? 

Cheers, Nap.

    user@host:[22:38]$ make
    [  1%] Generating lex.yy.cc
    [  3%] Generating pddl+.cpp
    /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/parsing/pddl+.yacc: conflicts: 1 shift/reduce, 4 reduce/reduce
    sed: 1: "/Users/nap/Programming/ ...": extra characters at the end of n command
    Scanning dependencies of target ParsePDDL
    [  5%] Building CXX object src/VALfiles/parsing/CMakeFiles/ParsePDDL.dir/pddl+.o
    [  7%] Building CXX object src/VALfiles/parsing/CMakeFiles/ParsePDDL.dir/ptree.o
    [  8%] Building CXX object src/VALfiles/parsing/CMakeFiles/ParsePDDL.dir/DebugWriteController.o
    [ 10%] Linking CXX static library libParsePDDL.a
    [ 10%] Built target ParsePDDL
    Scanning dependencies of target parser
    [ 12%] Building CXX object src/VALfiles/CMakeFiles/parser.dir/parse.o
    [ 14%] Linking CXX executable parser
    [ 14%] Built target parser
    Scanning dependencies of target Inst
    [ 16%] Building CXX object src/VALfiles/CMakeFiles/Inst.dir/SimpleEval.o
    [ 17%] Building CXX object src/VALfiles/CMakeFiles/Inst.dir/FastEnvironment.o
    [ 19%] Building CXX object src/VALfiles/CMakeFiles/Inst.dir/instantiation.o
    In file included from /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:31:
    In file included from /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/parsing/ptree.h:55:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:479:17: error: no matching function for call to object of type 'const Inst::ConstSymbolLT'
            {return static_cast<const _Compare&>(*this)(__x, __y.__cc.first);}
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:2007:17: note: in instantiation of member function 'std::__1::__map_value_compare<const VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>,
          Inst::ConstSymbolLT, true>::operator()' requested here
                if (value_comp()(__v, __nd->__value_))
                    ^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:1355:44: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<const VAL::const_symbol *, int>, std::__1::__map_value_compare<const
          VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>, std::__1::allocator<std::__1::__value_type<const VAL::const_symbol *, int> > >::__find_equal<const VAL::const_symbol *>' requested here
        __node_base_pointer& __child = __tree_.__find_equal(__parent, __k);
                                               ^
    /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:919:44: note: in instantiation of member function 'std::__1::map<const VAL::const_symbol *, int, Inst::ConstSymbolLT, std::__1::allocator<std::__1::pair<const VAL::const_symbol *const, int> > >::operator[]'
          requested here
                    parameterValuesToIndices[v][possibleParameterValues[v][j]] = j;
                                               ^
    /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:795:10: note: candidate function not viable: 'this' argument has type 'const Inst::ConstSymbolLT', but method is not marked const
        bool operator()(const VAL::const_symbol* const a, const VAL::const_symbol* const b) {
             ^
    In file included from /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:31:
    In file included from /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/parsing/ptree.h:55:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:476:17: error: no matching function for call to object of type 'const Inst::ConstSymbolLT'
            {return static_cast<const _Compare&>(*this)(__x.__cc.first, __y);}
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:2017:22: note: in instantiation of member function 'std::__1::__map_value_compare<const VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>,
          Inst::ConstSymbolLT, true>::operator()' requested here
                else if (value_comp()(__nd->__value_, __v))
                         ^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:1355:44: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<const VAL::const_symbol *, int>, std::__1::__map_value_compare<const
          VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>, std::__1::allocator<std::__1::__value_type<const VAL::const_symbol *, int> > >::__find_equal<const VAL::const_symbol *>' requested here
        __node_base_pointer& __child = __tree_.__find_equal(__parent, __k);
                                               ^
    /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:919:44: note: in instantiation of member function 'std::__1::map<const VAL::const_symbol *, int, Inst::ConstSymbolLT, std::__1::allocator<std::__1::pair<const VAL::const_symbol *const, int> > >::operator[]'
          requested here
                    parameterValuesToIndices[v][possibleParameterValues[v][j]] = j;
                                               ^
    /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:795:10: note: candidate function not viable: 'this' argument has type 'const Inst::ConstSymbolLT', but method is not marked const
        bool operator()(const VAL::const_symbol* const a, const VAL::const_symbol* const b) {
             ^
    In file included from /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:31:
    In file included from /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/parsing/ptree.h:55:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:442:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:2413:26: error: no matching function for call to object of type 'std::__1::__tree<std::__1::__value_type<const VAL::const_symbol *, int>, std::__1::__map_value_compare<const
          VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>, std::__1::allocator<std::__1::__value_type<const VAL::const_symbol *, int> > >::value_compare' (aka 'std::__1::__map_value_compare<const VAL::const_symbol *,
          std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>')
        if (__p != end() && !value_comp()(__v, *__p))
                             ^~~~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:1210:68: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<const VAL::const_symbol *, int>, std::__1::__map_value_compare<const
          VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>, std::__1::allocator<std::__1::__value_type<const VAL::const_symbol *, int> > >::find<const VAL::const_symbol *>' requested here
        iterator find(const key_type& __k)             {return __tree_.find(__k);}
                                                                       ^
    /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:1141:113: note: in instantiation of member function 'std::__1::map<const VAL::const_symbol *, int, Inst::ConstSymbolLT, std::__1::allocator<std::__1::pair<const VAL::const_symbol *const, int> > >::find'
          requested here
                                const pviLookup::iterator findEntry = parameterValuesToIndices[parameterIndex[aff]].find(asConst);
                                                                                                                    ^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:472:10: note: candidate function not viable: no known conversion from 'const VAL::const_symbol *const' to 'const std::__1::__value_type<const VAL::const_symbol *, int>' for 1st
          argument
        bool operator()(const _CP& __x, const _CP& __y) const
             ^
    In file included from /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:31:
    In file included from /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/parsing/ptree.h:55:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:442:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:2483:14: error: no matching function for call to object of type 'std::__1::__tree<std::__1::__value_type<const VAL::const_symbol *, int>, std::__1::__map_value_compare<const
          VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>, std::__1::allocator<std::__1::__value_type<const VAL::const_symbol *, int> > >::value_compare' (aka 'std::__1::__map_value_compare<const VAL::const_symbol *,
          std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>')
            if (!value_comp()(__root->__value_, __v))
                 ^~~~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:2412:20: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<const VAL::const_symbol *, int>,
          std::__1::__map_value_compare<const VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>, std::__1::allocator<std::__1::__value_type<const VAL::const_symbol *, int> > >::__lower_bound<const VAL::const_symbol *>' requested
          here
        iterator __p = __lower_bound(__v, __root(), __end_node());
                       ^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:1210:68: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<const VAL::const_symbol *, int>, std::__1::__map_value_compare<const
          VAL::const_symbol *, std::__1::__value_type<const VAL::const_symbol *, int>, Inst::ConstSymbolLT, true>, std::__1::allocator<std::__1::__value_type<const VAL::const_symbol *, int> > >::find<const VAL::const_symbol *>' requested here
        iterator find(const key_type& __k)             {return __tree_.find(__k);}
                                                                       ^
    /Users/nap/Programming/Planning/POPF/popf/src/VALfiles/instantiation.cpp:1141:113: note: in instantiation of member function 'std::__1::map<const VAL::const_symbol *, int, Inst::ConstSymbolLT, std::__1::allocator<std::__1::pair<const VAL::const_symbol *const, int> > >::find'
          requested here
                                const pviLookup::iterator findEntry = parameterValuesToIndices[parameterIndex[aff]].find(asConst);
                                                                                                                    ^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:472:10: note: candidate function not viable: no known conversion from 'const VAL::const_symbol *const' to 'const std::__1::__value_type<const VAL::const_symbol *, int>' for 2nd
          argument
        bool operator()(const _CP& __x, const _CP& __y) const
             ^
    4 errors generated.
    make[2]: *** [src/VALfiles/CMakeFiles/Inst.dir/instantiation.o] Error 1
    make[1]: *** [src/VALfiles/CMakeFiles/Inst.dir/all] Error 2
    make: *** [all] Error 2
    ~/Programming/Planning/POPF/popf/build (master~*=)
    user@host:[22:38]$

**Comment by aldukeman** [comment]
Sorry, I can't help with this. I only uploaded this and several other planners to GitHub because nobody else had and I was using it for my dissertation research. I haven't done anything with this in over a year. It was hard enough getting this old code to run on newer versions of Linux. A couple of the 2012 IPC planners worked on Mac, but most did not.

**Comment by Napoleon-BlownApart** [comment]
@aldukeman :  No problem.  I've actually got it to build and run (see my popf-MacOS under myaccount).
I've tested the parser, but now I need to test the planner using some sample problems.  If you could help me here by suggesting a suitable domain/problem to use from the IPC problem list, I would be grateful.

**Comment by aldukeman** [comment]
If I remember correctly, any of the domains from 2012 IPC will be fine. The BLOCKS domain, for example, would be a good starting point for testing "did this work"

**Comment by Napoleon-BlownApart** [comment]
Ok, done.  Looks like it's working:

    user@host:[15:27]$ ./popf domain.pddl probBLOCKS-4-0.pddl
    Constructing lookup tables: [10%] [20%] [30%] [40%] [50%] [60%] [70%] [80%] [90%] [100%]
    Post filtering unreachable actions:  [10%] [20%] [30%] [40%] [50%] [60%] [70%] [80%] [90%] [100%]
    b (8.000 | 0.001)b (4.000 | 0.003)b (2.000 | 0.004);;;; Solution Found
    ; Time 0.02
    0.000: (pick-up b)  [0.001]
    0.001: (stack b a)  [0.001]
    0.002: (pick-up c)  [0.001]
    0.003: (stack c b)  [0.001]
    0.004: (pick-up d)  [0.001]
    0.005: (stack d c)  [0.001]

I also successfully ran the MetricVehicle example from Fox/Long's PDDL2.1 definition (2003).

**Comment by sergey-lapin** [comment]
@Napoleon-BlownApart could you share how you fought this issue?

**Comment by Napoleon-BlownApart** [comment]
@sergey-lapin
I actually forked this to my own repo.
It's been a while, and MacOS has evolved, especially the Clang side of things so you might need to make some adjustments:

https://github.com/Napoleon-BlownApart/popf-MacOS

**Comment by sergey-lapin** [comment]
@Napoleon-BlownApart thank you for response, I am struggling with  
```
/Library/Developer/CommandLineTools/usr/include/c++/v1/map:494:17: error: no matching function for call to object of type 'const Inst::ConstSymbolLT'
        {return static_cast<const _Compare&>(*this)(__x, __y.__get_value().first);}
```
this kind of errors. How did you solve that?

**Comment by sergey-lapin** [comment]
@Napoleon-BlownApart thank you for response, I am struggling with  
```
/Library/Developer/CommandLineTools/usr/include/c++/v1/map:494:17: error: no matching function for call to object of type 'const Inst::ConstSymbolLT'
        {return static_cast<const _Compare&>(*this)(__x, __y.__get_value().first);}
```
these kind of errors. How did you solve that?
In your repo, issues is disabled so I keep the discussion here.
If I comment all places in instantiation.cpp file that throw such errors I can compile popf, but obviously it will work incorrectly. So I suppose you have figure out how to solve such problems, my guess something should be fixed in machine configuration, that's why I can not build your latest version, but it is ok on your side.

**Comment by Napoleon-BlownApart** [comment]
I'm getting the same error now.
I used GCC@8, which required the 'kludge'  I mentioned.  Though I now have gcc@10 as well and my Apple Clang is 12.0.0, I was still able to build it using gcc@8.
Try the following when in the parent folder of the repo:

    mkdir build
    cd build
    CC=/usr/local/opt/gcc@8/bin/gcc-8 CXX=/usr/local/opt/gcc@8/bin/g++-8 cmake ../
    CC=/usr/local/opt/gcc@8/bin/gcc-8 CXX=/usr/local/opt/gcc@8/bin/g++-8 make

This worked for me just now.
(You may need to adjust the paths to match the location of your gcc@8 install.)

**Comment by Napoleon-BlownApart** [comment]
I have pushed a new commit that includes the instructions above, and some changes I made some time ago whose reasons I am unable to remember right now without going through them in detail.
So, if the above doesn't produce the correct executables, you may wish to pull my fork again.

(I will also enable Issues once I figure out how to do that.)

**Comment by Napoleon-BlownApart** [comment]
Issues are now enabled.

**Comment by Napoleon-BlownApart** [comment]
Glad you got it working!
